ALTER TABLE TB_ENTRY    DROP CONSTRAINT ENTRY_PK;
ALTER TABLE TB_ENTRY    DROP CONSTRAINT ENTRY_FK1;
ALTER TABLE TB_ENTRY    DROP CONSTRAINT ENTRY_FK2;
ALTER TABLE TB_ENTRY    DROP CONSTRAINT ENTRY_FK3;
ALTER TABLE TB_CARD     DROP CONSTRAINT CARD_PK;
ALTER TABLE TB_ACCOUNT  DROP CONSTRAINT ACCOUNT_PK;
ALTER TABLE TB_ACCOUNT  DROP CONSTRAINT ACCOUNT_FK;
ALTER TABLE TB_CATEGORY DROP CONSTRAINT CATEGORY_PK;

DROP SEQUENCE CATEGORY_SEQ;
DROP SEQUENCE ACCOUNT_SEQ;
DROP SEQUENCE CARD_SEQ;
DROP SEQUENCE ENTRY_SEQ;

DROP TABLE TB_ACCOUNT;
DROP TABLE TB_CARD;
DROP TABLE TB_CATEGORY;
DROP TABLE TB_ENTRY;
