CREATE TABLE TB_CATEGORY(
  ID          INTEGER      NOT NULL,
  DESCRIPTION VARCHAR2(30) NOT NULL
);

CREATE TABLE TB_ACCOUNT(
  ID          INTEGER      NOT NULL,
  CATEGORY_ID INTEGER      NOT NULL,
  DESCRIPTION VARCHAR2(30) NOT NULL
);

CREATE TABLE TB_CARD(
  ID              INTEGER      NOT NULL,
  DESCRIPTION     VARCHAR2(30) NOT NULL,
  CARD_TYPE       VARCHAR2(10) NOT NULL,
  FLAG            VARCHAR2(20) NOT NULL,
  CLOSING_DAY     INTEGER,
  PAY_DAY         INTEGER, 
  EXPIRATION_DATE DATE         NOT NULL
);

CREATE TABLE TB_ENTRY(
  ID            INTEGER       NOT NULL,
  ENTRY_DATE    DATE          NOT NULL,
  CATEGORY_ID   INTEGER       NOT NULL,
  ACCOUNT_ID    INTEGER       NOT NULL,
  OPERATION     VARCHAR2(10)  NOT NULL,
  PAYMENT       VARCHAR2(10)  NOT NULL,
  CARD_ID       INTEGER,
  VALUE         NUMBER(10, 2) NOT NULL,
  OBSERVATION   VARCHAR2(100),
  RECEIPT_IMAGE BLOB
);

CREATE SEQUENCE CATEGORY_SEQ;
CREATE SEQUENCE ACCOUNT_SEQ;
CREATE SEQUENCE CARD_SEQ;
CREATE SEQUENCE ENTRY_SEQ;

ALTER TABLE TB_CATEGORY ADD CONSTRAINT CATEGORY_PK PRIMARY KEY(ID);
ALTER TABLE TB_ACCOUNT  ADD CONSTRAINT ACCOUNT_PK  PRIMARY KEY(ID);
ALTER TABLE TB_CARD     ADD CONSTRAINT CARD_PK     PRIMARY KEY(ID);
ALTER TABLE TB_ENTRY    ADD CONSTRAINT ENTRY_PK    PRIMARY KEY(ID);

ALTER TABLE TB_ACCOUNT ADD CONSTRAINT ACCOUNT_FK FOREIGN KEY(CATEGORY_ID) REFERENCES TB_CATEGORY(ID);
ALTER TABLE TB_ENTRY   ADD CONSTRAINT ENTRY_FK1  FOREIGN KEY(CATEGORY_ID) REFERENCES TB_CATEGORY(ID);
ALTER TABLE TB_ENTRY   ADD CONSTRAINT ENTRY_FK2  FOREIGN KEY(ACCOUNT_ID)  REFERENCES TB_ACCOUNT(ID);
ALTER TABLE TB_ENTRY   ADD CONSTRAINT ENTRY_FK3  FOREIGN KEY(CARD_ID)     REFERENCES TB_CARD(ID);

ALTER TABLE TB_CATEGORY ADD UNIQUE(DESCRIPTION);
ALTER TABLE TB_ACCOUNT ADD UNIQUE(DESCRIPTION);
ALTER TABLE TB_CARD ADD UNIQUE(DESCRIPTION);